name: Pre-Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: pre-release

jobs:
  qa:
    name: 🔹 QA
    permissions:
      contents: read
      packages: read
    uses: oliversalzburg/workflows/.github/workflows/qa-npm-package.yml@main

  pre-release:
    if: github.event_name == 'workflow_dispatch'
    name: 🔹 Publish
    needs: qa
    permissions:
      contents: write
      id-token: write
      packages: write
      pages: write
      pull-requests: read
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    uses: oliversalzburg/workflows/.github/workflows/publish-npm-package.yml@main
    with:
      has-mkdocs: false
      has-github-pages: false
      is-canary: true
      is-nightly: false
      publish-github-release: true
      release-tag: dev
